### PR TITLE
Fix anchor to retrieving deleted documents

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by flimzy** [comment]
This doesn't appear to fix a link--the link looks the same to me. It seems to just move it. Was that the intention? If so, maybe the description can be updated to explain why this is helpful?

**Comment by nono** [comment]
In the ` DELETE /{db}/{docid}` section, there is a link called "Retrieving deleted documents". When clicking on it, we are sent to a section that is not about retrieving deleted documents, but about retrieving attachments. I have moved the anchor, so that the link will go to the right section (the one called "Retrieving Deleted Documents").

**Comment by flimzy** [comment]
Ah, makes sense! Thanks for the explanation.

**Comment by flimzy** [comment]
+1

**Pull request merged**
