### PR TITLE
Small grammar fixes

### PR DESCRIPTION
**Pull request by yaronyg**
These are just small, easy, hopefully non-controversial grammar fixes.

The definition of URI refers to RFC 2396. But RFC 2396 is obsolete. It has been replaced by RFC 3986.

RFC 2822 has been obsoleted and replaced with RFC 5322

### CODE REVIEW

**Comment by kxepal** [comment]
Thanks a lot for your fixes! However, this change causes breaks [style guidlines](https://github.com/apache/couchdb-documentation/blob/master/src/contributing.rst#the-guidelines) in many ways.

Here is a full list of problems:

```
/home/kxepal/projects/couchdb/asf/couchdb-documentation/src/replication/protocol.rst
  line 123 : too long (84 > 80) line
    Changes Feed, the Replicator doesn't close the connection, but awaits new change

  line 144 : too long (81 > 80) line
HTTP endpoints, and run requests with the same parameters to provide a completely

  line 148 : too long (81 > 80) line
or Pull Replication. However, while such solutions could also run the Replication

  line 250 : trailing whitespace detected!
In case of a non-existent Target, the Replicator MAY make a :put:`/{db}` 

  line 278 : trailing whitespace detected!
:statuscode:`401` or a :statuscode:`403` error. Such errors SHOULD be expected 

  line 514 : trailing whitespace detected!
The Replication ID generation algorithm is implementation specific. Whatever 

  line 516 : too long (83 > 80) line
Replicator, for example, uses the following factors in generating a Replication ID:

  line 538 : too long (82 > 80) line
the Replication Log from both Source and Target using :get:`/{db}/_local/{docid}`:

  line 671 : too long (89 > 80) line
then the Replicator MUST determine their common ancestry by following the next algorithm:

  line 677 : too long (87 > 80) line
- In case of mismatch, iterate over the ``history`` collection to search for the latest

  line 750 : too long (84 > 80) line
the Source's :ref:`Changes Feed <changes>` by using a :get:`/{db}/_changes` request.

  line 940 : too long (85 > 80) line
but only for Revisions that do not exist in Target and are REQUIRED to be transferred

  line 982 : too long (87 > 80) line
When there are no more changes left to process and no more Documents left to replicate,

  line 983 : too long (82 > 80) line
the Replicator finishes the Replication process. If Replication wasn't Continuous,

  line 984 : too long (81 > 80) line
the Replicator MAY return a response to client with statistics about the process.

  line 1128 : too long (82 > 80) line
To fetch the Document the Replicator will make a :get:`/{db}/{docid}` request with

  line 1137 : too long (85 > 80) line
  then the Document MUST be returned for this Revision. Otherwise, Source MUST return

  line 1138 : trailing whitespace detected!
  an object with the single field ``missing`` with the missed Revision as the value. 

  line 1138 : too long (84 > 80) line
  an object with the single field ``missing`` with the missed Revision as the value.

  line 1139 : too long (84 > 80) line
  In case the Document contains attachments, Source MUST return information only for

  line 1140 : too long (82 > 80) line
  those ones that had been changed (added or updated) since the specified Revision

  line 1141 : too long (83 > 80) line
  values. If an attachment was deleted, the Document MUST NOT have stub information

  line 1146 : too long (84 > 80) line
  This parameter solves a race condition problem where the requested Document may be

  line 1151 : too long (84 > 80) line
specifies a different mime type. The :mimetype:`multipart/mixed` content type allows

  line 1155 : too long (82 > 80) line
encoded strings which are very ineffective for transfer and processing operations.

  line 1157 : too long (84 > 80) line
With a :mimetype:`multipart/mixed` response the Replicator handles multiple Document

  line 1160 : too long (86 > 80) line
more effective: the Document ALWAYS goes before its attachments, so the Replicator has

  line 1161 : too long (83 > 80) line
no need to process all the data to map related Documents-Attachments and may handle

  line 1264 : too long (81 > 80) line
stack size could be limited by number of Documents or bytes of handled JSON data.

  line 1283 : trailing whitespace detected!
:post:`/{db}/_bulk_docs` request to Target with payload containing a JSON object 

  line 1287 : too long (85 > 80) line
  These Documents MUST contain the ``_revisions`` field that holds a list of the full

  line 1361 : too long (82 > 80) line
If the Document has been stored successfully, the list item MUST contain the field

  line 1365 : too long (81 > 80) line
Document updating failure isn't fatal as Target MAY reject the update for its own

  line 1368 : too long (84 > 80) line
etc.). The Replicator SHOULD NOT retry uploading rejected documents unless there are

  line 1408 : too long (82 > 80) line
There is a special optimization case when then Replicator WILL NOT use bulk upload

  line 1419 : trailing whitespace detected!
a request allows one to easily stream the Document and all its attachments 

  line 1501 : too long (91 > 80) line
come with a different status code. For instance, in the case when the Document is rejected,

  line 1528 : too long (87 > 80) line
issues a :post:`/{db}/_ensure_full_commit` request to ensure that every transferred bit

  line 1530 : too long (88 > 80) line
:statuscode:`201` response with a JSON object containing the following mandatory fields:

  line 1564 : too long (81 > 80) line
Since batches of changes were uploaded and committed successfully, the Replicator

  line 1565 : too long (87 > 80) line
updates the Replication Log both on Source and Target recording the current Replication

  line 1566 : too long (92 > 80) line
state. This operation is REQUIRED so that in the case of Replication failure the replication

  line 1690 : too long (82 > 80) line
Once a batch of changes had been processed and transferred to Target successfully,

  line 1691 : trailing whitespace detected!
the Replicator can continue to listen to the Changes Feed for new changes. If there 

  line 1691 : too long (83 > 80) line
the Replicator can continue to listen to the Changes Feed for new changes. If there

  line 1694 : too long (85 > 80) line
For Continuous Replication, the Replicator MUST continue to wait for new changes from

  line 1703 : too long (85 > 80) line
occur. The Replicator SHOULD NOT count every HTTP request failure as a *fatal error*.

  line 1734 : trailing whitespace detected!
does not contain acceptable credentials then the Peer MUST respond with the 

  line 1748 : trailing whitespace detected!
sufficient permissions to perform the operation then the Peer 

  line 1774 : trailing whitespace detected!
If an unsupported method was used then the Peer MUST respond with a 

  line 1787 : trailing whitespace detected!
A resource conflict error occurs when there are concurrent updates of the same 

  line 1788 : trailing whitespace detected!
resource by multiple clients. In this case the Peer MUST respond with a HTTP 

  line 1818 : too long (86 > 80) line
continue Replication. In this case the Replicator MUST return a HTTP :statuscode:`500`

  line 1834 : too long (81 > 80) line
- Try to work with a connection pool and make parallel/multiple requests whenever

make: *** [check] Error 1
```

Once they'll be fixed, I merge your PR with pleasure!

**Comment by kxepal** [comment]
You may rebase your PR against current master to let Travis CI check all the bits.

**Comment by yaronyg** [comment]
I am running on windows and I tried make.bat doctest from the src directory but got a failure because it says "Build name doctest not registered". Eventually I figured out how to manually just run "python ext\linter.py src" from the MakeFile and that worked. But in any case it would be useful to have a link in the style guide that explains how to run the linter.

I'm going to close this PR and submit a separate one from my new repo. I fixed all the linter issues so hopefully now it will be fine.

**Comment by kxepal** [comment]
@yaronyg good points. I'll add reference to linter and fix windows support as well. Thanks!

**Pull request closed without merging**
