### PR TITLE
remove documentation about couch_peruser app

### PR DESCRIPTION
**Pull request by jo**
since this does not work anymore in 2.0.

### CODE REVIEW

**Comment by michellephung** [comment]
@jo can you pull in the latest and rebase? we updated the travis tests and now this pr should pass

**Comment by jo** [comment]
done

**Comment by michellephung** [comment]
I feel a bit fearful to merge this, since the email on user mailing thread. I will ask on irc if its okay to merge. i hope thats ok. i know it's been a while since you opened the pr. i hope thats okay. thanks for opening it :) btw.

**Comment by jo** [comment]
Thank you @michellephung!

**Comment by janl** [comment]
@KlausTrainer didn’t you fix this for 2.0?

**Comment by KlausTrainer** [comment]
@janl I implemented the feature with the intention to be released in 2.0. However, I haven't touched or tested it since the time it landed on the master branch (which was quite some time before the 2.0 release). So I didn't take notice of it being broken or incomplete maybe. (I'm currently following the project only sporadically; i.e., sometimes I scan the mailing lists.)

I apologize for pushing this feature, and then stopping to own it shortly afterwards! I know how this can be annoying :(

**Comment by michellephung** [comment]
no worries!! @KlausTrainer, what would you recommend here for this pr? leave it in? i saw that there was an email on the user mailing list a few days ago, and i wasnt sure if maybe leaving this up might help someone hack, even if its not a full feature

**Comment by wohali** [comment]
While CouchDB has a plan to supplement couch-peruser in the 3.0+ timeframe, if we can fix couch-peruser for 2.0 that'd be nice. I don't know, to be honest. That said I don't want to ship 2.1.0 with a broken feature. (2.1.0 is probably a couple of months away, summer at latest.)

@KlausTrainer if you don't think you'll get to this soon, we should probably archive the documentation and the implementation.

**Comment by wohali** [comment]
We're fixing peruser, hopefully for 2.1 (see https://github.com/apache/couchdb/pull/570).

As such I am closing this PR.

**Pull request closed without merging**
