### PR TITLE
welcome

### PR DESCRIPTION
**Pull request by stleon**
new version

### CODE REVIEW

**Comment by nickva** [comment]
+1 

I noticed trailing whitespace change on line 43 or so, it is currently preventing some Travis checks from passing. Let's fix that and I'll merge it

Thanks @stleon !

**Comment by stleon** [comment]
@nickva done

**Comment by nickva** [comment]
@stleon Thank you. Merged to master.

**Comment by stleon** [comment]
@nickva can you merge new changes?

**Comment by nickva** [comment]
@stleon Done. Sorry for the delay. Thank you for your help!

**Pull request merged**
