### PR TITLE
Update local replication documentation

### PR DESCRIPTION
**Pull request by flimzy**
Followup from [this slack conversation](https://couchdb.slack.com/archives/C49LEE7NW/p1562409911483700) with @janl, to update the replication documentation for the new post-2.x requirement for full URLs in replication source and target.

### CODE REVIEW

**Comment by flimzy** [comment]
Before this is merged, following the above linked Slack conversation, @rnewson pointed out that local replications _should_ still work for the `_replicate` endpoint, but weren't in my case (perhaps due to a bug, or perhaps due to the way the Docker image works).

I intend to file a bug about this, when I have time to document a solid reproduction case.  But before we document that fully-qualified URLs are required for all replications, we should ensure that this is the intention--or fix the code to honor the old behavior in all cases.

**Comment by nickva** [comment]
What happens with `_replicate` replications is that we perform a "hack" where we translate "local" looking like endpoint names into fully qualified URL ones:

https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd.erl#L406-L418

We don't know the actual server URL (since we could be behind a proxy) so we just look at what port and address the local CouchDB server is listening on, then also re-use the authorization and cookie params from the _replicate request.

**Comment by nickva** [comment]
I think we should mentioned that `_replicate` endpoint  is behaving differently from `_replicator` docs in that `_replicate` will transform local endpoints into remote ones by pre-pending the address and port CouchDB server listening on. So if CouchDB is listening on address `127.0.0.1`, port `1234` then a local endpoint like `source_db` would become a remote endpoint with the url of 'http://127.0.0.1:1234/source_db`.

And then maybe a note that behavior is deprecated in 3.x and will be removed in 4.x

**Comment by janl** [comment]
@flimzy are you interested in getting this updated for 3.0 which is really close now?

**Comment by wohali** [comment]
We need this for 3.0, so if @flimzy can't do it, we should take it up ourselves.

**Comment by flimzy** [comment]
Sorry for not responding. On principle, I'm happy to do this, but I've just started a new job, and am traveling a lot until mid Feb, so will probably have limited bandwidth to dedicate to it.

**Comment by wohali** [comment]
@flimzy thanks, I'll take it across the finish line!

@nickva please see my latest push and let me know if this meets your expectations?

**Comment by nickva** [comment]
@wohali looks good! Thank you.

I'lll merge it

**Pull request merged**
