### PR TITLE
Additions to _find and _index from original Mango docs PR

### PR DESCRIPTION
**Pull request by lornajane**
This replaces #31 which added the Mango docs, but mostly it adds anything from that PR that wasn't already covered in #55 so this version now includes more examples and words in places.  I've also tried to fix at least as many indentation weirdnesses as I've created!

One major difference was that #31 covered indexes with `type=text` which these docs didn't - I've added this content in but I wanted to flag this just in case there's a reason why it shouldn't be included in this context.

### CODE REVIEW

**Comment by lornajane** [comment]
Is there an easy way to run those syntax checks locally, please?  The build works OK but I didn't realise there was more I should have checked.  (we need a contributing file, I've got it on my todo list!)

**Comment by wohali** [comment]
Yes - run `make check`.

**Comment by lornajane** [comment]
Let me know if I should squash these commits, I fixed one check and managed to break another!

**Comment by wohali** [comment]
Yes, please squash! 

----- Original Message -----

**Comment by wohali** [comment]
+1, thanks!

**Pull request merged**
