### PR TITLE
_db_updates heartbeat option is a number

### PR DESCRIPTION
**Pull request by jo**
like for _changes feed

### CODE REVIEW

**Comment by jo** [comment]
also rebased.

**Comment by jo** [comment]
CI still [fails for some Python versions](https://travis-ci.org/apache/couchdb-documentation/builds/190953345) - any ideas? @michellephung

**Comment by michellephung** [comment]
/home/travis/build/apache/couchdb-documentation/src/api/server/common.rst:233: WARNING: undefined label: db_updates/longpoll (if the link has no caption the label must precede a section header)

its a syntax error -- this link might help: http://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html

I haven't tried it locally yet though. I can try this weekend

**Comment by jo** [comment]
Thanks for the link! I have just removed the references.

**Pull request merged**
