### PR TITLE
Mention [cors] max_age

### PR DESCRIPTION
**Pull request by klaemo**
## Overview

The [2.1 release notes](https://docs.couchdb.org/en/latest/whatsnew/2.1.html) mentioned fixing this parameter. I didn't even know it existed, but it's quite helpful to improve replication performance as `OPTIONS` requests can be cached.

## Testing recommendations

Is it correct what I've written?

## Checklist

- [x] Documentation is written and is accurate;
- [x] `make check` passes with no errors
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the commit hash once this PR is rebased and merged

### CODE REVIEW

**Comment by klaemo** [comment]
I’m not familiar with the process. Can this and #388 be merged and who would do that? 🙂

**Comment by flimzy** [comment]
All PRs need two approvals before being merged. Once someone else approves it (ideally someone who can vouch for the factual accuracy), it can be merged by anyone with the appropriate access.

**Comment by wohali** [comment]
@flimzy actually, our bylaws only state a[ single +1 is necessary](http://couchdb.apache.org/bylaws.html#rtc):

> Typically, CouchDB uses the Review-Then-Commit (RTC) model of code collaboration. RTC allows work to proceed on separate feature or bugfix branches, and requires at least one other developer to review and approve the changes before they are committed to a release branch.

So you can go ahead and merge these if you think they're good to go, @flimzy.

**Comment by wohali** [comment]
Looks fine.

@klaemo Did you see my email re: docker? Thanks for your updates to your repo...still wondering if it makes sense to de-publish klaemo/couchdb from Docker Hub. Sorry to hijack this issue for it but you never replied to my email :(

-Joan

**Comment by flimzy** [comment]
Thanks for the refresher course on the bilaws, @wohali. I'll keep that in mind in the future. On this particular pair of PRs, I didn't feel qualified to judge their technical merits, without doing more research, so I'm glad you were able to look them over, too.

**Comment by klaemo** [comment]
@wohali I must have missed that email 😢 So sorry about that. I opened https://github.com/apache/couchdb-docker/issues/133 to discuss whether it's time to remove klaemo/couchdb or if it could other images/deployments that still build on it.

**Pull request merged**
