### PR TITLE
Update changes feed documentation

### PR DESCRIPTION
**Pull request by flimzy**

### CODE REVIEW

**Comment by nickva** [comment]
Wonder if there is a way to improve this one a bit. I like the enumeration of possible values for `feed` inline, but notice that below is a whole section describing each one. Every section has an anchor so perhaps we could create a ref to it, after a brief description.

So maybe something like **normal** all past changes returned immediately :ref:`normal` ...?

For longpoll if we keep the short description maybe mention first that it is like normal mostly, "unless we give it a since=now or the last rev explicitly".

**Comment by flimzy** [comment]
Good suggestions, @nickva. I'll make those changes when I can--it may be a while, as I'm on semi-vacation right now. So don't think I'm avoiding the changes :)

**Comment by nickva** [comment]
@flimzy, Thank you so much for helping with the documentation. Your contributions are very much appreciated. Enjoy your vacation!

**Comment by flimzy** [comment]
@nickva Let me know how you feel about my recent changes.

**Comment by nickva** [comment]
Looks great @flimzy! Really appreciate your work. Thank you very much!

+1

**Pull request merged**
