### PR TITLE
Clarify and expand on GET /_session response

### PR DESCRIPTION
**Pull request by flimzy**
## Overview

Grammar clarifications, and expanding of response details for `GET /_session` documentation.

## Checklist

- [x] Documentation is written and is accurate;
- [x] `make check` passes with no errors
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the commit hash once this PR is rebased and merged

### CODE REVIEW

**Comment by nickva** [comment]
+1

**Comment by flimzy** [comment]
I thought I had access to merge my own PRs now, but apparently I don't yet (any longer?) so I guess I'll need someone else to merge this for me :)

**Comment by wohali** [comment]
@flimzy you need to visit https://gitbox.apache.org/ to link your accounts, and wait about an hour. Give it a shot.

**Comment by nickva** [comment]
@flimzy I won't merge it yet, let's use this as a test to see if you can merge after the gitbox setup.

**Comment by flimzy** [comment]
I've got the button now. Thanks for the patience, @wohali  & @nickva

**Pull request merged**
