### PR TITLE
Update info on cluster configuration

### PR DESCRIPTION
**Pull request by eiri**
## Overview

This is an update for a section on a cluster configuration, removing mention of outdated configuration parameters and specifying how number of reads and writes before a success code is returned defined in a cluster.

## Related Pull Requests

apache/couchdb#837

## Checklist

- [x] Documentation is written and is accurate;
- [x] `make check` passes with no errors
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the commit hash once this PR is rebased and merged

### CODE REVIEW

**Comment by davisp** [comment]
+1

**Comment by wohali** [comment]
@eiri Can you please update this file as well, please? https://github.com/apache/couchdb-documentation/blob/master/src/api/database/common.rst

**Comment by eiri** [comment]
@wohali Sure, but do I do that now or after we'll get that new changes in new release? Sorry, I'm not familiar with release cycle of documentation on "stable".

**Comment by wohali** [comment]
`docs.couchdb.org` is built off of tags as well as master. By default you get redirected to `docs.couchdb.org/en/2.1.0` but you can specify `/en/latest` or `/en/master` to see HEAD. So no worries about making updates right now :)

**Pull request merged**
